---
title: "Assingment-Two"
output: html_document
date: "2022-10-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# U7117486 Assignment Two 

## Load in packages
```{r}
library(pacman)
p_load(bookdown, tidyverse, ggforce, flextable, latex2exp, png, magick, metafor) 
```

## Reading in the csv file 
```{r}
data <- read_csv("OA_activitydat_20190302_BIOL3207.csv")
data
```

## Omitting N/A data
```{r}
data <- na.omit(data)
data
```

## Drop irrelevant columns
```{r}
data <- subset(data, select = -c(comment, loc))
data
```

## Creating a summary of results 
```{r summaryTab}
summary1<- filter(data, treatment == "control") %>% group_by(species) %>% summarise(mean(activity), sd(activity), n())
colnames(summary1) <- c("Species", "ctrl.mean", "ctrl.sd", "ctrl.n")

summary2<- filter(data, treatment == "CO2") %>% group_by(species) %>% summarise(mean(activity), sd(activity), n())
colnames(summary2) <- c("Species", "oa.mean", "oa.sd", "oa.n")

summary <- merge(summary1, summary2)
summary
```
## Reading in the clark paper meta data
```{r}
clark_meta <- read_csv("clark_paper_data.csv")
clark_meta
```

## Binding the summary results to the study information meta data provided
```{r}
clark_data <- bind_cols(clark_meta, summary)
clark_data
```

## Reading in the larger meta data set 
```{r}
ocean_meta <- read_csv("ocean_meta_data.csv")
ocean_meta
```

## Binding the clark data to the larger meta data set 
```{r}
clark_data[, c(12)] <- sapply(clark_data[, c(12)], as.character)
clark_data[, c(7)] <- sapply(clark_data[, c(7)], as.character)
clark_data[, c(8)] <- sapply(clark_data[, c(8)], as.character)

merged_data <- bind_rows(ocean_meta, clark_data)
merged_data
```